"""Improving business

Revision ID: 15ba3345f063
Revises: 05cb81f078a7
Create Date: 2025-08-16 23:10:13.794090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ba3345f063'
down_revision: Union[str, Sequence[str], None] = '05cb81f078a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('address', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('city', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('state', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('country', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('activiry_area', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'activiry_area')
    op.drop_column('businesses', 'country')
    op.drop_column('businesses', 'state')
    op.drop_column('businesses', 'city')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###
