"""decsription

Revision ID: 2701afe2e4ff
Revises: ffe3128f85fc
Create Date: 2025-08-26 13:15:04.993825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2701afe2e4ff'
down_revision: Union[str, Sequence[str], None] = 'ffe3128f85fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('tagline', sa.String(), nullable=True))
    op.drop_column('businesses', 'brief')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('brief', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'tagline')
    op.drop_column('businesses', 'description')
    # ### end Alembic commands ###
