"""activity areas and services

Revision ID: ffe3128f85fc
Revises: a1b2c3d4e5f6
Create Date: 2025-08-26 12:52:01.087745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe3128f85fc'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_activity_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_area', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_activity_areas_activity_area'), 'business_activity_areas', ['activity_area'], unique=False)
    op.create_index(op.f('ix_business_activity_areas_business_id'), 'business_activity_areas', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_activity_areas_id'), 'business_activity_areas', ['id'], unique=False)
    op.create_table('business_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_services_business_id'), 'business_services', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_services_id'), 'business_services', ['id'], unique=False)
    op.create_index(op.f('ix_business_services_service'), 'business_services', ['service'], unique=False)
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_businesses_owner_id'), 'businesses', ['owner_id'], unique=False)
    op.drop_column('businesses', 'activiry_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('activiry_area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_businesses_owner_id'), table_name='businesses')
    op.alter_column('businesses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_business_services_service'), table_name='business_services')
    op.drop_index(op.f('ix_business_services_id'), table_name='business_services')
    op.drop_index(op.f('ix_business_services_business_id'), table_name='business_services')
    op.drop_table('business_services')
    op.drop_index(op.f('ix_business_activity_areas_id'), table_name='business_activity_areas')
    op.drop_index(op.f('ix_business_activity_areas_business_id'), table_name='business_activity_areas')
    op.drop_index(op.f('ix_business_activity_areas_activity_area'), table_name='business_activity_areas')
    op.drop_table('business_activity_areas')
    # ### end Alembic commands ###
